name = "SciMLStructures"
uuid = "53ae85a6-f571-4167-b2af-e1d143709226"
authors = ["SciML"]
version = "1.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"

[compat]
ArrayInterface = "7.11"
Aqua = "0.8"
DataStructures = "0.18"
Functors = "0.4"
SafeTestsets = "0.1"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "SafeTestsets"]
